branch-defaults:
  master:
    environment: vst-io-dev
    group_suffix: null
global:
  application_name: vst-io
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
